db-url: jdbc:h2:mem:api-store
db-username: sa
db-password:
db-driver-class: org.h2.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          allow_jdbc_metadata_access: false
  sql:
    init:
      platform: h2
  flyway:
    password:
    user: sa
    url: jdbc:h2:mem:api-store
    baselineOnMigrate: true
