server:
  port: 9030
#Connection profiles
spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
springdoc:
  swagger-ui:
    path: /v1/api-docs